services:
  piper:
    image: rhasspy/wyoming-piper
    container_name: piper
    restart: unless-stopped
    command: ["--voice", "en_GB-alan-medium","--length-scale","0.6"]
    ports:
      - "5000:5000" # HTTP TTS endpoint
      - "10200:10200" # Wyoming protocol
    volumes:
      - piper_data:/data
volumes:
  piper_data:
